from typing import Protocol

from orders_clean_architecture.domain.entities import Order


class OrderRepository(Protocol):
    def add(self, order: Order) -> None: ...
    def get_by_id(self, order_id: str) -> Order | None: ...
    def list_all(self) -> list[Order]: ...
